#!/usr/bin/env bash

# Format the submission
pip3 install pyparsing
python3 /autograder/source/autograder/remove_comments.py /autograder/submission/*.arr

# Run the actual autograder
cd /autograder/source/autograder
python3 run_autograder.py

# Download latest results->gradescope report converter
cd "/autograder/result-processing"
git reset HEAD --hard
git pull

# Compile the results
cd /autograder/results
jq --slurp -c '.' */results.json > raw_results.json

# Convert results to gradescope's format and location
npm i @types/node
ts-node "/autograder/result-processing/gradescope_report.ts" raw_results.json results.json /autograder/source/points.json
